version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Lint codebase
          command: npm run lint
      - run:
          name: Lint fix
          command: npm run lint:fix
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results
